pulp-platform/common_cells

CHANGELOG.md, src/cdc_2phase.sv
Verilator does not like positional generic arguments.
=> Fix verilator make generics explicit

CHANGELOG.md, src/deprecated/pulp_sync_wedge.sv, src/sync.sv, src/sync_wedge.sv
Pulp_synch_wegde is restructured to use the pulp_sync cells. could you please merge into the master?
=> sync_wedge: Use existing synchroniser

Bender.yml, CHANGELOG.md, README.md, src/fall_through_register.sv, src/fifo_v3.sv, src/id_queue.sv, src/stream_filter.sv, src/stream_fork.sv, src/stream_register.sv, src_files.yml, test/fifo_tb.sv, test/graycode_tb.sv, test/id_queue_synth.sv, test/id_queue_tb.sv, test/simulate.sh, test/synth.sh, test/synth_bench.sv, test/waves/id_queue.do
Four new modules(stream fork, stream filter, fall-through register, and ID queue) call for a new minor release! Additionally, this brings a few clean-ups and an effort to bring back continuous synthesis and simulation regression runs.
Reviewers:
- @msfschaffner mainly for the [ID queue](https://github.com/pulp-platform/common_cells/commit/78096178b5a4058925ebe191fa0176e5c5fb7f7c)
- @fabianschuiki mainly for the Bender- and CI-related improvements (https://github.com/pulp-platform/common_cells/commit/5ae503bd61ea11cf5d5e7a1f8a579b4b59a57f01, https://github.com/pulp-platform/common_cells/commit/6cf0933e6ec7209472a8c9ee05dff1aac8606f1d, https://github.com/pulp-platform/common_cells/commit/534cde5b4a02a80df62c8e6561f38b181292ed6e). Maybe you have a quick fix for the currently failing …
=> Release 1.11

src/lzc.sv
The alternative Verilator implementation was diverging from the actual
LZC implementation. This has lead to simulation mismatches.
=> lzc: Fix misbehaving Verilator alternative

src/rr_arb_tree.sv
I worked on the assertions of the `rr_arb_tree` module, after encountering a few violations (especially with the `LOCK_IN` feature turned on). After checking the module with a formal verification tool, more problems appeared, as follows:
- Given the `always_ff` blocks, I believe the correct reset signal is `(!rst_ni) || (flush_i)`, otherwise the properties would leave the value of `flush_i` floating. A default reset signal avoids repetition of this expression.
- Property `lock_req` seems more like an assumption than an assertion, as it controls the behavior of signals outside the module (through `req_tmp`).
- Possible typo in `req1`.
=> rr_arb_tree assertions

src/spill_register.sv
Added a parameter which bypasses the spill register.
=> added bypass parameter to spill register

Bender.yml, CHANGELOG.md, README.md, src/addr_decode.sv, test/addr_decode_tb.sv, test/waves/addr_decode_tb.wave.do
Addition of an address map to index decoder module
=> Address decoder

src/popcount.sv
This will be used by [Ariane/scoreboard](https://github.com/pulp-platform/ariane/blob/master/src/scoreboard.sv#L167-L172) to support `NR_COMMIT_PORTS == 1`.
=> Update popcount to support input of width 1

CHANGELOG.md, src/cdc_fifo_gray.sv
Largely follows these guidelines: http://www.sunburst-design.com/papers/CummingsSNUG2008Boston_CDC.pdf
=> cdc_fifo_gray: Switch to a safe CDC FIFO design

Bender.yml, CHANGELOG.md, src_files.yml
Pull request for issue [#63](https://github.com/pulp-platform/common_cells/issues/63)
- Added missing sources in `Bender.yml` and `src_files.yml`
=> Bender.yml: Add missing sources

CHANGELOG.md, src/addr_decode.sv
`addr_decode`: Handle degenerate `NoIndices == 32'd1`
=> addr_decode: Handle degenerate NoIndices == 1

.gitignore, .travis.yml, Bender.yml, CHANGELOG.md, Makefile, README.md, ci/install-verilator.sh, src/ecc_decode.sv, src/ecc_encode.sv, src/ecc_pkg.sv, src_files.yml, test/.gitignore, test/ecc/ecc.cpp, test/ecc/ecc.h, test/ecc/ecc_decode.cpp, test/ecc/ecc_encode.cpp, test/ecc_synth.sv, test/synth.sh, test/synth_bench.sv
Earlier last year I was experimenting a bit with ECC. I thought this module might be interesting for somebody (e.g. error correction on an L2 for example). This module can detect up to two errors and correct a single error.
As the testbench is built using Verilator and C++ I also added the tests to CI. 
Happy to have your input on this.
=> Add ECC module

src/id_queue.sv
Apparently one needs to annotate the type for `xcelium` to work.
=> id_queue: Xcelium fixes

CHANGELOG.md, src/stream_xbar.sv
Fix for a missing string argument.
=> stream_xbar: Add missing argument in assertion error string

src_files.yml
Fixes parsing order of files as addr_decode.sv depends on cf_math_pkg.sv
=> src_files.yml addr_decode depends on cf_math

.github/verible-lint-matcher.json, .github/workflows/ci.yml, lint/common_cells.style.waiver
This adds a lint action to GitHub's workflow. A custom matcher annotates
the lint result back on the pull request.
=> lint: Add style linting to CI

src_files.yml
* Move addr_decode to lvl 1
* Move lzc to lvl 1 (align with `bender.yml`)
* Move id_queue to lvl 2 (align with `bender.yml`)
* Fix graycode module names
* Introduce isochronous_spilL_register
* Introduce new stream components
=> src_files: Fix dependencies

Bender.yml, CHANGELOG.md, src/cc_onehot.sv
A fast implementation of `$onehot()`.
=> Add `cc_onehot` module

Bender.yml, CHANGELOG.md, README.md, src/id_queue.sv, src/isochronous_4phase_handshake.sv, src/isochronous_spill_register.sv, test/isochronous_crossing_tb.sv, test/simulate.sh
Another member of the isochronous group: A four-phase handshake.
=> isochronous_4phase_handshake: Add implementation

CHANGELOG.md
Create a new release with the latest changes.
Unfortunately, I don't have permission to push directly to master. So either we ff-merge this, or @zarubaf, you could cherry-pick this commit.
=> Release v1.23.0

src_files.yml
=> Small typofix for clk div in src_files.yml

src_files.yml
Some newly added files, mostly related to CDCs, seem to have not made it into src_files.yml
=> Align src_files.yml with Bender

.github/workflows/ci.yml, lint/common_cells.style.waiver, src/onehot_to_bin.sv, src/popcount.sv
Update verible CI to use chipsalliance github action, fix minor lint warnings
=> Update CI and fix lint

Bender.yml, README.md, common_cells.core, src/cdc_reset_ctrlr.sv, src/clk_mux_glitch_free.sv, src_files.yml, test/clk_mux_glitch_free_tb.sv
Depends on https://github.com/pulp-platform/tech_cells_generic/pull/27
=> Add glitch free clock multiplexer

Bender.yml, README.md, src/stream_join.sv, src/stream_join_dynamic.sv, src_files.yml
This PR addresses feature request (1) from issue #150.
=> Add stream_join_dynamic IP

.github/workflows/gitlab-ci.yml
This allows automatic runs from external repos.
=> ci: Change gitlab-ci trigger to pull_request_target

src/id_queue.sv
Add a parameter in ID QUEUE to generate multiple lookup ports.
=> Make the number of compare ports in id_queue parametric

test/cdc_2phase_clearable_tb.sv, test/clk_int_div_static_tb.sv, test/fifo_tb.sv
Workarounds for verilator issues:
https://github.com/verilator/verilator/issues/5979
https://github.com/verilator/verilator/issues/5981 / https://github.com/verilator/verilator/issues/4263
=> Verilator compile fixes
