pulp-platform/common_cells

src_files.yml

I'm using `generic_fifo_adv`, but it doesn't seem to be listed in `src_files.yml`.

Export generic_fifo_adv

---

CHANGELOG.md
src/deprecated/generic_fifo.sv

The original `generic_fifo` guaranteed that `valid_i` could be asserted even though the FIFO instance was full (i.e., `~grant_o`) and that `grant_i` could be asserted even though the FIFO instance was empty (i.e., `~valid_o`).  Before this commit, the `generic_fifo` in this repository did not fulfill these guarantees (they caused assertion violations in the internally instantiated FIFO).  This commit fixes this without changing any other properties.

generic_fifo: Fix `valid_i` and `grant_i` guarantees

---

CHANGELOG.md
src/lzc.sv

Some synthesis tools that shall not be named don't support streaming operators as ternary operands.

:space_invader: Fix streaming operator in ternary for synth

---

Bender.yml
CHANGELOG.md
src/cf_math_pkg.sv

This package contains a collection of mathematical functions that are commonly used when defining the value of constants in HDL code.  These functions are implemented as Verilog constants functions.  Introduced in Verilog 2001 (IEEE Std 1364-2001), a constant function (§ 10.3.5) is a function whose value can be evaluated at compile time or during elaboration.  A constant function must be called with arguments that are constants.

Add cf_math_pkg: Constant Function Implementations of Mathematical Functions for HDL Elaboration

---

Bender.yml
CHANGELOG.md
README.md
src/counter.sv
src/delta_counter.sv
src/max_counter.sv
src_files.yml

I propose to extend the counter in this repository by three features:
- Latch overflows if the `LATCH_OVERFLOW` parameter is set.
- A variable counter step / delta, implemented as `delta_counter` (`counter` now just instantiates a `delta_counter` with a hardwired delta of `1`). I created a new module to not break the existing `counter`.
- A counter that latches the maximum value, implemented as `max_counter`.

Extend counter features: overflow latch, variable delta, maximum latch

---

src/lzc.sv

The cast `$clog2(WIDTH)'(0)` causes errors in older synthesis tools, and is probably not what was intended here. The code casts the integer value 0 to a constant function call, which seems to work properly only with the `$bits()` function across tools (if at all).
I believe the goal was to be explicit about the width of the signal, which would require the replication operator, as suggested in the commit, i.e. `{($clog2(WIDTH)){1'b0}}`
Just putting a literal `0` there should also work I think, as this is cast to the proper width implicitly. I am aware that the cast was put in place initially because of linter warnings, but the initial code contained an assignment to `'0` which is different from the integer literal `0`, so maybe try that first to reduce the code clutter.

:space_invader: Fix "cast to constant" in LZC

---

src/onehot_to_bin.sv

The immediate assertion in `onehot_to_bin.sv` was inside an initial block, and was only checked at the beginning of the simulation.
Because the module has no clock, I added the "final" attribute to postpone the evaluation of the assertion until the signals settle. I checked it with ModelSim 10.6, but previous versions of the simulator might have issues with final deferred assertions.

[onehot-to-bin] Fix immediate assertion

---

src/stream_demux.sv
src/stream_mux.sv

Change localparam to parameter to fix quartus compile error. This error also has been discussed in https://stackoverflow.com/questions/29717467/modelsim-wrong-scope-for-localparam

fix altera quartus compile error

---

test/simulate.sh
test/synth.sh

`bender vsim` is not supported on the latest bender [release](https://github.com/fabianschuiki/bender/releases/tag/v0.13.3) anymore. Use `bender script vsim` instead.

test: Update to `bender script`

---

.gitignore
formal/Makefile
formal/README.md
formal/counter.sby
formal/counter_properties.sv
formal/fall_through_register.sby
formal/fall_through_register_properties.sv
formal/fifo_v3.sby
formal/fifo_v3_properties.sv

Leverage `Yosys` and `SymbiYosys` (commercial version with the verific
parser) to formally proof properties of `fifo_v3`. We don't touch the IPs themselves by using SystemVerilog's `bind`.

Add formal verification properties for some IPs

---

Bender.yml
CHANGELOG.md
README.md
src/cb_filter.sv
src/sub_per_hash.sv
test/cb_filter_tb.sv
test/sub_per_hash_tb.sv
test/waves/cb_filter_tb.wave.do
test/waves/sub_per_hash_tb.wave.do

Added two new modules and it's respective test-benches:
- `sub_per_hash.sv` : Implements a fully seedable substitution-permutation non-crypto hash function.
- `cb_filter.sv`: Implements a counting-bloom-filter with combinational lookup

Substitution Permutation Hash Function and Counting Bloom Filter

---

CHANGELOG.md
src/lzc.sv

The LZC uses `$clog2(WIDTH)` throughout the implementation, which raises some problems when `WIDTH = 1`. This version generates a degenerated version of the LZC for this special case.

lzc: handle degenerate case when WIDTH=1

---

src/lzc.sv

Some [older] tools don't parse parameters used for specifying bit-widths of
signals correctly unless they're enclosed in parentheses.

:art: Add parens around width params

---

src/id_queue.sv

There are `HT_CAPACITY` registers behind the `head_tail_q` signal, and the value of `HT_CAPACITY` need not necessarily be the same as `CAPACITY`.

id_queue: Fix generation of `head_tail_q` registers

---

src_files.yml

missing `incdirs` field in src_files killed IPApproX.

src_files: added include dir

---

Bender.yml
CHANGELOG.md
README.md
src/stream_fifo.sv
src_files.yml

Just a trivial wrapper for fifo_v3 - I found it handy to have around.

add stream_fifo: fifo_v3 with rdy/vld interface

---

Bender.yml
CHANGELOG.md
README.md
src/stream_fork_dynamic.sv
src/stream_join.sv

This adds two stream modules:
* `stream_fork_dynamic`: Fork a stream partially with a selection mask, wrapper around stream_fork.
* `stream_join`: Join multiple streams into one, output handshake will only go high if all input streams are valid.

Add stream modules

---

Bender.yml
CHANGELOG.md
README.md
src/isochronous_spill_register.sv
src/stream_intf.sv
test/isochronous_spill_register_tb.sv
test/stream_test.sv

This module works similarly to the `spill_register` as it cuts any combinatorial paths but additionally allows to couple two clock domains with an isochronous clock (i.e., two clocks which do not vary in phase but vary in a constant integer factor in frequency).
The implementation concept is similar to the CDC FIFO but without any synchronization mechanisms as we do not need to deal with metastability (timing covered by STA).

Isochronous spill register

---

ips_list.yml
src/cdc_fifo_2phase.sv

Fixes a problem with verilator having trouble parsing an unnamed parameter binding and copies dependencies from the Bender.yml to ips_list.yml

Fix verilator error and IPApprox missing dependency

---

CHANGELOG.md
src/stream_register.sv

Changed $size() to $bits() in stream_register.sv
Closes #92.

stream_register: Fix DATA_WIDTH of instantiated FIFO

---

src/rr_arb_tree.sv

fixed type casting in a copy/paste typo, should not change functionality, might avoid a warning

fixed type casting

---

CHANGELOG.md
README.md
include/common_cells/assertions.svh

Analogously to the register macro definitions in include header
`registers.svh`, this commit adds macro definitions for assertions.

assertions: Add assertion header

---

common_cells.core
include/common_cells/assertions.svh
src/addr_decode.sv
src/rr_arb_tree.sv

Replaced the previously added NDEBUG define with a tool-specific XSIM define analogous to how the VERILATOR define is used

Replace NDEBUG define with an XSIM guard

---

CHANGELOG.md
src/id_queue.sv

The [styleguide](https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#dont-cares-xs) strongly discourages the use of don't cares. 
Eg. When using the output of `id_queue` to index into arrays the simulation output gets spamed with [warnings](https://github.com/pulp-platform/axi/issues/150).
Changes:
* `'x` in `id_queue` are replaced by `'0`.
* The localparams `HtIdxWidth` and `LdIdxWidth` in `id_queue` are now calculated with `cf_math_pkg::idx_width()`.
#106 should also be adapted, as there are also `'x` in default assignments/resets.

src/id_queue.sv: Specify dont-cares

---

Bender.yml
CHANGELOG.md
ips_list.yml
test/addr_decode_tb.sv
test/cb_filter_tb.sv
test/cdc_2phase_tb.sv
test/cdc_fifo_tb.sv
test/fifo_tb.sv
test/graycode_tb.sv
test/id_queue_tb.sv
test/popcount_tb.sv
test/rr_arb_tree_tb.sv
test/stream_omega_net_tb.sv
test/stream_to_mem_tb.sv
test/stream_xbar_tb.sv
test/sub_per_hash_tb.sv

Updates the following dependencies:
- `tech_cells_generic` (v0.1.1 -> v0.2.3)
- `common_verification` (v0.1.1 -> v0.2.0)
- requires renaming of some parameters

Bump common_verification and tech_cells_generic dependency

---

src/id_queue.sv
src/stream_fork.sv
src/stream_mux.sv

Verific is a stickler for syntax, and the usage of $fatal in places seemed to disregard the first argument.

Fix a syntax error with  that broke verific

---

src/rr_arb_tree.sv

When `rr_arb_tree` is locked, allow flushing the decision (i.e. do not throw an error). Otherwise, asserting `flush_i` with `LockIn` set will fail.

rr_arb_tree: update assertion to allow flushing locked decision

---

CHANGELOG.md
README.md
include/common_cells/registers.svh

Merged explicit and implicit macros into `` `FF `` and `` `FFL `` for
asynchronous FFs without and with load-enable, respectively. The old
macros `` `FFARN `` and `` `FFLARN `` are retained for compatibility but
a deprecation notice was added to them.

registers.svh: Merge explicit and implicit macros

---

include/common_cells/registers.svh

As discussed in #115 here is a tidied-up version.

registers: Optionally disable Synopsys macros

---

src/spill_register.sv

The introduction of a new port to an existing module is not backward compatible and
thus breaks every other repository that uses the spill_registers from common
cells. I guess the intention was to not introduce this port and have the
spill_register module act as just a wrapper.
After merging this commit, we should immediately release a new minor version to restore compatibility.

Fix port list copy paste bug

---

src/id_queue.sv

When working on Fenrir we realized that the id_queue cannot simultaneously have stuff inserted and output. This commit fixes it, increasing the maximal achievable utilization from 50% to 100%. Tested with the provided testbench and in-system.

src/id_queue.sv: Enables simultaneous input and output

---

CHANGELOG.md
src/isochronous_4phase_handshake.sv
src/isochronous_spill_register.sv

The `disable iff` conditions in these assertions did not account for the active-low reset polarity.

iso-crossings: Fix reset polarity in assertions

---

CHANGELOG.md
src/sub_per_hash.sv

The latest Verilator version has issues with some constructs used in the `sub_per_hash` module: 
``` 
%Error: common_cells/src/sub_per_hash.sv:54:42: Expecting expression to be constant, but can't determine constant for FUNCREF 'get_permutations'
: ... In instance common_cells/src/sub_per_hash.sv:109:23: ... Location of non-constant ASSIGN: Array select LHS isn't simple variable
common_cells/src/sub_per_hash.sv:54:42: ... Called from get_permutations() with parameters:
seed = 32'h47df4
```
The issue is that `XorStages` and `PERMUTATIONS` are declared as `localparam`'s, whose value depends on the result of a function. The issue is solved by declaring those two variables as signals.
This fix is between `ifdef VERILATOR` guards, but there is no issue with using this construct with other EDA …

Verilator issue with sub_per_hash

---

Bender.yml
CHANGELOG.md
README.md
src/edge_propagator_ack.sv
src_files.yml

Added a version of the edge propagator that has an acknowledge port which flags if the edge has actually propagated to the receiving side. Useful if the initiating circuit can only safely continue if the described condition is met.

Edge propagator ack

---

Bender.yml
CHANGELOG.md
README.md
src/cdc_2phase.sv
src/cdc_2phase_clearable.sv
src/cdc_4phase.sv
src/cdc_fifo_2phase.sv
src/cdc_fifo_gray.sv
src/cdc_fifo_gray_clearable.sv
src/cdc_reset_ctrlr.sv
src/cdc_reset_ctrlr_pkg.sv
src/sync.sv
test/cdc_2phase_clearable_tb.sv
test/cdc_fifo_clearable_tb.sv

In some architectures, there is a need to support one-sided resets/clears of a CDC instance (e.g. a debug module resetting itself using asnychronous JTAG). This is highly non-trivial to do in a safe manner since resetting the state of a CDC breaks all sorts of CDC  protocol assumptions and might introduce reset-domain-crossing problems ([see discussion in related riscv-dbg issue](https://github.com/pulp-platform/riscv-dbg/issues/120)). 
This PR contains my first draft of a safe cdc reset sequencer module that I use for clearable versions of the 2-phase and gray FIFO CDC. The reset sequencer provides an isolate and clear signal to each clock domain and transitions through the reset phases very similar to what a power management module would do after power-gating (except here there is no …

Clearable cdcs

---

src/stream_delay.sv

The stream_delay module optionally contains an LFSR to randomize the delays. If we instantiate more than one of these modules as verification IP, it would be useful being able to set the seed of each LFSR individually. This PR exposes the LFSR seed parameter to the toplevel and assigns it the default value to maintain backward compatibility.

Add optional seed parameter to stream_delay module

---

CHANGELOG.md
src/id_queue.sv

VCS can not handle the way the `mask_t` is defined for specific instances. Since the `mask_t` and the `data_t` need the same width anyway, and the tools have problems with this call, I propose we just reuse the `data_t` directly.
Furthermore, I would argue that we should use a width parameter instead of a type parameter for `data_t` in the future. This requires an interface change, but the current implementation could run into problems if the `data_t` is defined as a multidimensional array. On [line 369](https://github.com/pulp-platform/common_cells/blob/master/src/id_queue.sv#L369), we loop over all bits in `data_t`, which only works for 1D vectors or packed structs, afaik. We could also just flatten the `data_t` inside the module to avoid changing the interface. @andreaskurth What do …

Fix toolproblems in `id_queue`

---

CHANGELOG.md
common_cells.core

It seems `common_cells.core` is out of date for some time now. However there is at least[ one other IP](https://github.com/pulp-platform/axi/blob/db457aa8d8996d87ca72486a9b15873042e04d38/axi.core#L54) in PULP that expects newer version of `common_cells` through FuseSoc. This PR should fix that.

Fix FuseSoc core version

---

Bender.yml
README.md
common_cells.core
src/stream_fifo_optimal_wrap.sv
src_files.yml

Based on synthesis numbers spill registers are superior in terms of area and timing to FIFOs of depth 2 whilst having the same semantics. A wrapper was created to select the optimal configuration.

stream_fifo_wrap: Add a wrapper that optimally selects either a spill register or a fifo

---

CHANGELOG.md
test/cb_filter_tb.sv
test/stream_register_tb.sv
test/sub_per_hash_tb.sv

The `program` blocks in some testbenches cause elaboration issues in VCS. Since we do not rely on the scheduling guarantees they provide, they are functionally redundant, and thus we can remove them.

Remove `program` blocks from testbenches for VCS compatibility

---

CHANGELOG.md
src/rstgen_bypass.sv

The current `rstgen_bypass` uses behaviorally-inferred multiplexing logic to switch between test mode and regular operation. Although `test_mode_i` is usually quasistatic, the generated reset may exhibit glitches if this does not hold for any reason or if the inferred multiplexing logic produces glitches when the reset itself toggles.

Use glitch-free `tc_clk_mux` muxes in `rstgen_bypass`

---

Bender.yml
CHANGELOG.md

Remove `cb_filter` and `cb_filter_pkg` from from Vivado IP packager project sources due to compatibility issues. Note that this does *not* remove it from sources when using Vivado by itself.

Exclude `cb_filter` from Vivado IP packager projects

---

src/stream_register.sv

The use of `fifo_full` to determine readiness caused a stall on every second clock cycle. This commit replaces the FIFO implementation with a simple register with proper propagation of the `ready` signal.
Furthermore, bubbles in the stream are resolved combinatorially now.

stream_register: Replace FIFO with FFs

---

Bender.yml
CHANGELOG.md
README.md
common_cells.core
src/addr_decode.sv
src/addr_decode_napot.sv
src_files.yml

Add `addr_decode_napot`, which uses a base address and mask instead of a start and end address.
TODO:

Add `addr_decode_napot`

---

CHANGELOG.md
src/addr_decode.sv

This allows for use of an address map where the top end address is zero, indicating the end of the address space (or wrap around as there are no longer any bits available).

Allow out-of-bounds top end address in addr_map

---

src/fall_through_register.sv

The `fall_through_register` still uses the deprecated `fifo_v2`.  This PR updates it to `fifo_v3`. Fixes #84.

Update `fall_through_register`'s fifo to `fifo_v3`

---

Bender.yml
common_cells.core
src/read.sv
src_files.yml

This module is used when you want to keep an internal signal after synthesis elaboration.
For example to refer to it in the UPFs, or any other reason.

add dummy assign

---

CHANGELOG.md
src/stream_fifo_optimal_wrap.sv

In my opinion, the `Full push` and the `Empty pop` assertions are unnecessary in the `stream_fifo_optimal_wrap`. Empty pops and Full pushes are prevented inside the modules anyway.
Those asserts for example require that the `ready` can only be asserted when the `valid` is asserted, which is an unnecessary restriction in my opinion. The AXI ready signals e.g. are asserted independently of the valid signals.
What do you think @thommythomaso?

`stream_fifo_optimal_wrap`: Remove assertions

---

src/cb_filter.sv
src/id_queue.sv
src/lfsr.sv
src/lfsr_16bit.sv
src/lfsr_8bit.sv
src/lzc.sv

Dear @meggiman and @niwis , thanks for reviewing and suggesting changes wrt #164 - 
Ok, I think it is clean enough until sv2v or yosys get better at supporting **sv**,
meanwhile, I added a couple more ifdef for VERILATOR.
To be 100% fair, I do not know whether VERILATOR supports them or not, but I did not want to add ifdef YOSYS or SV2V, so I borrowed VERILATOR
Is that ok?

add more ifdef verilator

---

include/common_cells/registers.svh

Removes the ternary operator from load-enable FF macros as this causes synthesis of a physical feedback path from the current state `__q` to the next state `__d` in synthesis.

registers: Update load-enable FF macros

---

src/clk_int_div.sv
test/clk_int_div_tb.sv

The FSM of the configurable clock divider contains an unnecessary gating condition to only allow divider configuration while the output clock is enabled. Although configuration during enabled output clock is perfectly safe since the module temporarily gates itself to avoid any output glitches, it might still be desirable from an application point of view to disable the output clock for a longer time period and re-enable it with a different clock divider value. With the current implementation this is not possible since at least one or two clock edges of the old clock period might still escape the module before the reconfiguration with enabled output clock takes effect.
This PR fixes this and adds a new test to the TB to check if the divider can be configured correctly while `en_i` is …

Allow clock divider configuration while clock is disabled

---

src/mem_to_banks.sv

With this change, mem_to_banks assumes at least 1 cycle latency to the memory bank, but cuts a possible timing loop (e.g., when in axi_to_mem).

Fix HideStrb feature of mem_to_banks

---

src/fifo_v3.sv
test/fifo_tb.sv

I was investigating `fifo_v3` with lint tools. There are no bugs just a few complaints about dead code.
When DEPTH is power of two then the  `if` branch for the write/read pointer updates are not needed (pointers just roll over). Can be e.g. seen by just deleting the branches and re-running the testbenches

Trivial FIFO TB additions

---

Bender.yml
README.md
common_cells.core
src/shift_reg.sv
src/shift_reg_gated.sv
src_files.yml

A shift register with clock gating

Add shift_register_gated

---

lint/common_cells.style.waiver
src/clk_int_div.sv
test/clk_int_div_tb.sv

Instead of storing div_i directly in the internal register div_q we normalize the value to be strictly larger than 0. This avoids the deadlock issue when preloading with 0. Furthermore this commit removes all combinational checks on the phase of `ungated_output_clock` to avoid hold issues in synthesis. This checks were required to wait until the clock enable signal has been latched by the ICG. Now, we instead use a dedicated flip-flop that tracks the current status of the output clock gate.
This fixes #172.

Fix deadlock on div_i == 0 and avoid hold issues on ungated_output_clock

---

src/clk_mux_glitch_free.sv
src/rstgen_bypass.sv
test/clk_mux_glitch_free_tb.sv

This PR give the `clk_mux_glitch_free` module the ability to propagate a selected clock even during reset assertion.

clk_mux_glitch_free: add support for clock output during reset assertion

---

src/popcount.sv
test/popcount_tb.sv

The popcount implementation so far used a recursive implementation using a binary adder tree. However, experiments using reasonably modern synthesis tools show that the logic optimization heuristics achieve the same or better results in less compilation time when the popcount logic is described in a flat for loop instead of nested modules.
While simplifying the popcount implementation, this change also fixes #187

Simplify popcount and add proper support for all input widths

---

.gitlab-ci.yml
Bender.yml
README.md
lint/common_cells.style.waiver
src/clk_int_div.sv
src/clk_int_div_static.sv
test/clk_int_div_static_tb.sv

This PR adds a convenience wrapper for the `clk_int_div` module that ties of the inputs to provide a static clock divider with a fixed division value. The PR also contains a TB for this new module that verifies the clock divider for various different parametrizations.

Clk int div static

---

src/stream_delay.sv

Allow larger counts for `stream_delay`. Based on #185.

stream_delay: Allow larger counts

---

src/unread.sv

Synthesizing with Vivado results in the module `unread` being a black box and subsequent implementation fails.
This patch proposes to assign the input to a fake net to mitigate this error.

unread: Assign do dummy net when synthesizing with vivado

---

src/mem_to_banks.sv
src/mem_to_banks_detailed.sv

Verilator crashes parsing mem_to_banks.sv because of a divide by zero if NumBanks is 0

Set bank count to nonzero in default parameter to avoid div by 0

---

Bender.yml
README.md
src/multiaddr_decode.sv
src_files.yml

This IP provides address-based multicasting capabilities. By providing a mask together with the address, we can compactly represent a set of addresses to compare with the address map.
A question might be if we want to merge this functionality in the `addr_decode` module or keep it separate as is the case now. Integration of the `addr_decode_napot` with `addr_decode` was already a step in this direction, as the prior uses the same encoding for the address map as the `multiaddr_decode` module.

Add multiaddr_decode IP

---

Bender.yml
README.md
common_cells.core
src/addr_decode.sv
src/addr_decode_dync.sv
src/addr_decode_napot.sv
src_files.yml

Transient invalid rule configs during online configuration of the IP currently cause warning messages and could even throw fatals. This PR adds a `DYNamic Configuration (DYNC)` version of the IP with one additional input, bringing the IP to a well-known state and silencing all continuous assertions during reconfiguration.

addr_decode: Add a variant suited for online configuration

---

src/onehot_to_bin.sv

As mentioned in the issue, this would make the assignment more generic and compile clean with strict compile in few simulators.

Fix width mismatch assignment issue #191

---

src/plru_tree.sv

Verilator currently does not properly support automatic variables declared inside a combinatorial block if these are only used in some branches (it incorrectly emits a latch warning for these variables). This PR moves the update logic and the PLRU output logic in `plru_tree.sv` into two functions to avoid this issue.
Additionally, some linting tools (e.g. Spyglass) complain when individual bits of integers are accessed via indexing (as is commonly done with logic vectors), which occurs within the current implementation of `plru_tree.sv` in two instances, e.g.:
https://github.com/pulp-platform/common_cells/blob/52f83eed3e92ed4ea5f79774854b0cb68618dcbb/src/plru_tree.sv#L94
Instead of extracting bit 0 of `new_index` by indexing (i.e., via `new_index[0]`) this PR casts the integer to a width …

Fix tool issues with automatic variables in PLRU tree

---

src/stream_xbar.sv

PR https://github.com/pulp-platform/common_cells/pull/200 fixed an issue in the `stream_xbar` assertions, effectively enabling them when reset is not asserted:
https://github.com/pulp-platform/common_cells/pull/200/files#diff-872c7e67b01645ac7cc6cecf1dbb01b73f1b1882d8bb77089dcb27570c35ac23L169
Thanks to this, a bug in one of the assertions was revealed:
https://github.com/pulp-platform/common_cells/blob/52f83eed3e92ed4ea5f79774854b0cb68618dcbb/src/stream_xbar.sv#L172-L176
`sel_oup_t` can represent values in the range [0, `NumOut`). Because of this, if for example `NumOut` is 32, the comparison will reduce to `sel_i[i] < 0` which will never be satisfied.
This PR fixes this issue.

`stream_xbar`: Fix non-existing output assertion

---

src/plru_tree.sv

@niwis Another thing that just came to my mind: it might make sense to add an assertion to verify that the output is always onehot.

plru_tree: Assert output is onehot

---

src/stream_omega_net.sv

Fixes the same problem described in https://github.com/pulp-platform/common_cells/pull/204, but for the `stream_omega_net` IP.
This urges a new release, as v1.33.0 broke certain IPs (RTL simulation of the Snitch cluster) which previously worked with v1.32.0.

`stream_omega_net`: Fix non-existing output assertion

---

src/stream_omega_net.sv
src/stream_xbar.sv

Fixing the reset polarity of assertions in `stream_xbar` and `stream_omega_net` (#200) uncovered numerous assertion failures in our  designs using `common_cells`.  One assertion failure we observe may result from intentional, functionally correct design.  
`stream_xbar` and `stream_omega_net` are commonly used for in-cycle banked SRAM interconnects (e.g. PULP TCDM), wherein parts of a valid payload may freely change if they are not relevant to that payload.
The most common example is a shared request channel for reads and writes. The write data is always part of the payload, but on reads (i.e. when the write enable in the payload is low), it is irrelevant to the request. Thus, efficient designs may opt to hardwire write data to a write-specific datapath, which may result in write data …

stream-xbar: Add payload stability assertion mask

---

src/id_queue.sv

With the parameter enabled, cut the path from the output pop and the input gnt with minimal impact to buffering.

id_queue: Add parameter to cut a critical path

---

src/stream_arbiter_flushable.sv

Setting `LockIn` while `ExtPrio = 1'b1` is disallowed by the `rr_arb_tree` and has no effect. Furthermore, locking a decision with a possibly lower priority violates the intent of the priority arbiter.
Therefore, clear the `LockIn` parameter for the priority arbiter.
Fixes #221.

stream_arbiter_flushable: Do not lock prio arbiter

---

src/cdc_2phase.sv
src/cdc_fifo_2phase.sv
src/fifo_v3.sv
src/lossy_valid_to_stream.sv
src/shift_reg_gated.sv
src/spill_register_flushable.sv
src/stream_register.sv

Several of the modules in this repository allow the user to specify a custom data type. Yet, the reset value for data registers is always `'0`, which causes linter errors if the data type is, for instance, an enum.
This PR casts all `'0` reset values for data registers to the respective data type (e.g., `T'('0)`), thus avoiding linter warnings.

Cast `'0` reset values to data type

---

src/delta_counter.sv

In the previous version of the code, the flip-flop was described non-idiomatically, using a ternary operator to implement the asynchronous reset. Some synthesis tools do not properly interpret this as a reset, resulting in gates being inserted on the reset network, which is undesirable.

[delta_counter] Attach reset properly to overflow FF

---

src/addr_decode_dync.sv
src/multiaddr_decode.sv

The `addr_decode_dync` and `multiaddr_decode` modules feature some complex assertions (actually `assume`s to be precise) that are quite complex — too complex for Verilator it seems, which fails in unpredictable ways when these modules are present. Therefore, this PR disables those assertions in Verilator (based on whether the `VERILATOR` pre-processor macro is defined).

Avoid wide signals in sensitivity lists of immediate assertions

---

include/common_cells/assertions.svh
src/addr_decode_dync.sv
src/cb_filter.sv
src/cdc_2phase_clearable.sv
src/cdc_fifo_2phase.sv
src/cdc_fifo_gray.sv
src/cdc_fifo_gray_clearable.sv
src/exp_backoff.sv
src/fifo_v3.sv
src/id_queue.sv
src/isochronous_4phase_handshake.sv
src/isochronous_spill_register.sv
src/lfsr.sv
src/lfsr_16bit.sv
src/lfsr_8bit.sv
src/lzc.sv
src/mem_to_banks_detailed.sv
src/multiaddr_decode.sv
src/onehot_to_bin.sv
src/plru_tree.sv
src/rr_arb_tree.sv
src/spill_register_flushable.sv
src/stream_fork.sv
src/stream_fork_dynamic.sv
src/stream_intf.sv
src/stream_join_dynamic.sv
src/stream_mux.sv
src/stream_omega_net.sv
src/stream_to_mem.sv
src/stream_xbar.sv

This PR replaces all assertions (and assumes) in the common cells sources with macros from [`assertions.svh`](https://github.com/pulp-platform/common_cells/blob/master/include/common_cells/assertions.svh).
Additionally, the `assertions.svh` itself is modified as follows:
- Some defines (such as the guard block at the start of the header) are renamed for consistency and to avoid name collisions in the same style as in [`registers.svh`](https://github.com/pulp-platform/common_cells/blob/master/include/common_cells/registers.svh).
- The `` `ifndef VERILATOR`` is removed because Verilator has supported assertions for a while now.
- An option to override any of the default defines that cause assertions to be turned off (such as `SYNTHESIS`) is added (so even if a tool defines, e.g., …

Replace all asserts & assumes with macros from `assertions.svh`

---

src/stream_join_dynamic.sv

Observed behavior: a successful handshake on the output ports asserts `ready=1` on all input ports regardless of `sel_i` selection. This leads to unwanted handshakes on the input channels which have `valid=1` but are not selected. This PR proposes a simple fix to ensure only selected input channels observe `ready=1`.

stream_join_dynamic: Assert inp readies only for selected streams

---

README.md

During my recent changes to the assertion macros in `assertions.svh` as part of #233, I missed that these are documented in the repository's README file. This PR updates the README to reflect those changes.

readme: Update documentation of assertion macros

---

src/addr_decode_dync.sv
src/multiaddr_decode.sv

While working on #233, I overlooked that the combinatorial blocks around the immediate assertions in `addr_decode_dync` and `multiaddr_decode` contain an unsynthesizable `$isunknown()` call. While the guard macros in `assertions.svh` do disable the assertions themselves when `SYNTHESIS` is defined, the `$isunknown` requires that the whole block is guarded as well. Sorry for missing this!

Guard unsynthesizable `$isunknown` with ifndef SYNTHESIS

---

include/common_cells/assertions.svh

Another day, another fix for PR #233. This time I realized that undefining a helper macro that is still needed later on is not a smart idea — turns out that due to this the assertion macros were not enabled so far.
Also, a comment in lowRISC's implementation made me realize that the helper macro can be useful outside of the header:
https://github.com/lowRISC/opentitan/blob/28af81ab6e41d9ee6b270f28c7e62761d6c62c31/hw/ip/prim/rtl/prim_assert.sv#L59-L60

assertions: Keep helper macros defined

---

src/delta_counter.sv

A recent fix to the reset logic in delta_counter 10dac0ff33 looks like it accidentally inverted the reset logic.

Fix inverted reset in delta_counter

---

src/fall_through_register.sv

The description of the `fall_through_register` says that it does not cut any combinatorial paths. 
This looks wrong, as the `ready` path seems actually cut (`ready_o` depends on `fifo_full` [only](https://github.com/pulp-platform/common_cells/blob/master/src/fall_through_register.sv#L53), which does [not depend on any other interface signal](https://github.com/pulp-platform/common_cells/blob/master/src/fifo_v3.sv#L57)).

Fix `fall_through_register` description

---

Bender.yml

The deprecated SRAM imported with `simulation` breaks with verilator. This PR excludes said module from being imported with `verilator`.

[Verilator] Don't import deprecated SRAM with verilator

---

src/id_queue.sv

The error has been reported in the past in a closed issue in PULPissimo:
https://github.com/pulp-platform/pulpissimo/issues/71#issuecomment-522698136
but is also triggered in other conditions (e.g., on work that is not yet open-source).
The fix is trivial.

Fix mismatch in id_queue triggering obscure errors in QuestaSim

---

src/id_queue.sv

This `always_comb` block previously consumed 9% of total simulation runtime for Cheshire on Verilator (pulp-platform/cheshire#230). With this change, this is reduced to a vanishing amount (reported as 0.00%).

id_queue: Simplify existence lookup for Verilator speed-up

---

README.md

Contributions:
- Add links to source files
- Mark `sram` IP as deprecated (source file was already in deprecated folder) and superseded by `tc_sram`

README.md: Add links to source files

---

Bender.yml
README.md
include/common_cells/assertions.svh
src/boxcar.sv
src/cf_math_pkg.sv
src/heaviside.sv
src/id_queue.sv
src/isochronous_spill_register.sv
src/lzc.sv
src/ring_buffer.sv
src/trip_counter.sv
src_files.yml

This PR implements the following contributions:
- Add an assertion to verify the stability of ready-valid interfaces.
- Add a `ring_buffer` IP. Uses a sequential write interface and a random-access read interface. Other variants could be implemented as well.
- Add a `trip_counter` IP. Resets automatically when it reaches a specified bound, useful e.g. for implementing hardware loop logic.
- Correct a bug in the documentation of the `lzc` IP.
- Add mask generation IPs (`heaviside` and `boxcar`), to encapsulate and abstract the bitwise expression logic to generate the masks. Also good for correctness and self-documentation.
Note: this is currently based on https://github.com/pulp-platform/common_cells/pull/247.

Add mask, `ring_buffer` and `trip_counter` IPs
